# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eeac0548f62efb17d5fb0a4f050e604eb10f3bbe356f2da96a0ca0f30bf079caad27bb04cc19bbbd863af21a47fd4fb9d456a6c9d2af9f1ae866ee6c238bd14e

test:
  secret_key_base: 607cfc2a98b9d321949953aff22040c6a3623e7bafd36bbb668df340a0a7d4adbab8c8fe18b446a84adebfe62c14ccd92b30b421b5c9f9776352dffa445caa69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
